version: "2"
services:
  generate-vectortiles:
    environment:
      BBOX: "-10, 36, 14.5, 54"
      OSM_MAX_TIMESTAMP : "2019-11-21T21:17:34Z"
      OSM_AREA_NAME: "france"
      MIN_ZOOM: "7"
      MAX_ZOOM: "9"
