version: "2"
services:
  generate-vectortiles:
    environment:
      BBOX: "-5.5517733, 41.1611155, 9.9282225, 51.4055721"
      OSM_MAX_TIMESTAMP : "2019-11-21T21:17:34Z"
      OSM_AREA_NAME: "france"
      MIN_ZOOM: "10"
      MAX_ZOOM: "14"
