#!/usr/bin/bash

set -e

docker-compose run --rm build bash -e -c "
    cd /data/pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v france-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v andorra-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v guernsey-jersey-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v luxembourg-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v belgium-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v spain-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v madagascar-latest.osm.pbf
"


rm -f pbf/saint_pierre_et_miquelon-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/north-america/saint_pierre_et_miquelon-latest.osm.pbf
rm -f pbf/martinique-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/central-america/martinique-latest.osm.pbf
rm -f pbf/guadeloupe.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/central-america/guadeloupe.osm.pbf
rm -f pbf/guyane-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/south-america/guyane-latest.osm.pbf
rm -f pbf/reunion-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/africa/reunion-latest.osm.pbf
rm -f pbf/mayotte-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/africa/mayotte-latest.osm.pbf
rm -f pbf/polynesie-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/oceania/polynesie-latest.osm.pbf


docker-compose run --rm build bash -e -c "
    cd /data/pbf
    osmium merge -v --progress \
        --overwrite -o merge.osm.pbf \
        france-latest.osm.pbf \
        andorra-latest.osm.pbf \
        guernsey-jersey-latest.osm.pbf \
        luxembourg-latest.osm.pbf \
        belgium-latest.osm.pbf \
        spain-latest.osm.pbf \
        madagascar-latest.osm.pbf \
        saint_pierre_et_miquelon-latest.osm.pbf \
        martinique-latest.osm.pbf \
        guadeloupe.osm.pbf \
        guyane-latest.osm.pbf \
        reunion-latest.osm.pbf \
        mayotte-latest.osm.pbf \
        polynesie-latest.osm.pbf
"

mkdir -p openmaptiles/data/
mv -f pbf/merge.osm.pbf openmaptiles/data/

cd openmaptiles
docker-compose down -v && \
rm -fr build
cd -

docker-compose run --rm build bash -e -c "
    ./ontology-build.sh && \\
    ruby ontology2layer.rb tourism \\
        ontology-tourism.json \\
        openmaptiles/layers/poi_tourism/poi_tourism.yaml \\
        openmaptiles/layers/poi_tourism/mapping.yaml \\
        openmaptiles/layers/poi_tourism/class.sql && \\
    ruby ontology2layer.rb city \\
        ontology-city.json \\
        openmaptiles/layers/poi_city/poi_city.yaml \\
        openmaptiles/layers/poi_city/mapping.yaml \\
        openmaptiles/layers/poi_city/class.sql \\
"

generate() {
    AREA=$1
    ZOOM_MIN=$2
    ZOOM_MAX=$3
    cp ../bbox/${AREA}-z${ZOOM_MIN}-z${ZOOM_MAX}.bbox data/merge.bbox && \
    sed -i "s/MIN_ZOOM.*/MIN_ZOOM=${ZOOM_MIN}/" .env && \
    sed -i "s/MAX_ZOOM.*/MAX_ZOOM=${ZOOM_MAX}/" .env && \
    make generate-tiles area=merge && \
    mv data/tiles.mbtiles ../mbtiles/openmaptiles-v3-${AREA}-z${ZOOM_MIN}-z${ZOOM_MAX}.mbtiles && \
}

cd openmaptiles && \
make && \
make start-db && \
make import-data && \
make import-osm area=merge && \
make import-sql && \
make import-wikidata && \
make analyze-db && \
generate("saint_pierre_et_miquelon", 7, 14) && \
generate("antilles", 7, 14) && \
generate("mayotte", 10, 14) && \
generate("reunion", 7, 14) && \
generate("polynesie", 7, 14) && \
generate("guyane", 7, 9) && \
generate("guyane", 10, 14) && \
generate("madagascar", 7, 9) && \
generate("madagascar", 10, 14) && \
generate("europe", 7, 9) && \
generate("europe", 10, 14) && \
cd ..


# 8m39,435s
docker-compose run --rm build bash -e -c "
    cd /data/mbtiles
    tile-join --no-tile-size-limit \
        --attribution '<a href=\"https://www.teritorio.fr/\" target=\"_blank\">&copy; Teritorio</a> <a href=\"https://www.openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles</a> <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors</a>' \
        --force -o teritorio-dev.mbtiles \
        openmaptiles-v3-z0-z6.mbtiles \
        openmaptiles-v3-europe-z7-z9.mbtiles \
        openmaptiles-v3-europe-z10-z14.mbtiles \
        openmaptiles-v3-saint_pierre_et_miquelon-z7-z14.mbtiles \
        openmaptiles-v3-antilles-z7-z14.mbtiles \
        openmaptiles-v3-mayotte-z10-z14.mbtiles \
        openmaptiles-v3-reunion-z7-z14.mbtiles \
        openmaptiles-v3-polynesie-z7-z14.mbtiles \
        openmaptiles-v3-guyane-z7-z9.mbtiles \
        openmaptiles-v3-guyane-z10-z14.mbtiles \
        openmaptiles-v3-madagascar-z7-z9.mbtiles \
        openmaptiles-v3-madagascar-z10-z14.mbtiles
"

cp ontology-tourism.json ./mbtiles/teritorio-tourism-ontology-dev.json
cp ontology-city.json ./mbtiles/teritorio-city-ontology-dev.json
