#!/usr/bin/bash

set -e

# Planet z0-z6

wget -P pbf https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf

docker-compose run --rm build bash -e -c "
    cd /data/pbf

    time osmium tags-filter planet-latest.osm.pbf w/highway=motorway,trunk --overwrite -o planet-highway-latest.osm.pbf
    time osmium tags-filter planet-latest.osm.pbf w/railway=rail --overwrite -o planet-rails-latest.osm.pbf
    time osmium tags-filter planet-latest.osm.pbf n/place=city,continent,country,island,ocean,sea,state --overwrite -o planet-places-latest.osm.pbf

    time osmium tags-filter planet-latest.osm.pbf a/boundary=administrative -R -f pbf | osmium tags-filter -F pbf - a/admin_level=1,2,3,4 -R --overwrite -o planet-boundary_noref-latest.osm.pbf
    time osmium getid planet-latest.osm.pbf -r -I planet-boundary_noref-latest.osm.pbf --overwrite -o planet-boundary-latest.osm.pbf

    time osmium tags-filter planet-latest.osm.pbf a/natural=water -R -f pbf | osmium tags-filter -F pbf - a/water=lake -R -f pbf | osmium tags-filter -F pbf - a/name=* -R --overwrite -o planet-lake_noref-latest.osm.pbf
    time osmium getid planet-latest.osm.pbf -r -I planet-lake_noref-latest.osm.pbf --overwrite -o planet-lake-latest.osm.pbf

    time osmium tags-filter planet-latest.osm.pbf a/leisure=nature_reserve a/boundary=national_park -R --overwrite -o planet-park_noref-latest.osm.pbf
    time osmium getid planet-latest.osm.pbf -r -I planet-park_noref-latest.osm.pbf --overwrite -o planet-park-latest.osm.pbf

    time osmium merge -v --progress \
        --overwrite -o planet-z0-z6.osm.pbf \
        planet-highway-latest.osm.pbf \
        planet-rails-latest.osm.pbf \
        planet-places-latest.osm.pbf \
        planet-boundary-latest.osm.pbf \
        planet-lake-latest.osm.pbf \
        planet-park-latest.osm.pbf
"

rm -f \
    pbf/planet-highway-latest.osm.pbf \
    pbf/planet-rails-latest.osm.pbf \
    pbf/planet-places-latest.osm.pbf \
    pbf/planet-boundary-latest.osm.pbf \
    pbf/planet-boundary_noref-latest.osm.pbf \
    pbf/planet-lake-latest.osm.pbf \
    pbf/planet-park-latest.osm.pbf \
    pbf/planet-lake_noref-latest.osm.pbf \
    pbf/planet-park_noref-latest.osm.pbf

generate() {
    ZOOM_MIN=$1
    ZOOM_MAX=$2
    JAVA_TOOL_OPTIONS="-Xmx2g" java -jar target/*with-deps.jar \
        --force \
        --osm-path=../pbf/planet-z0-z6.osm.pbf \
        --bounds=-180,-90,180,90 \
        --minzoom=${ZOOM_MIN} \
        --maxzoom=${ZOOM_MAX} \
        --output=../mbtiles/openmaptiles-v3-z${ZOOM_MIN}-z${ZOOM_MAX}.mbtiles
}

cd planetiler-openmaptiles && \
git checkout src/main/java/org/openmaptiles/generated/ && \
./scripts/regenerate-openmaptiles.sh openmaptiles file://`pwd`/../ && \
./mvnw clean package -Dmaven.test.skip --no-snapshot-updates && \
generate 0 6
