#!/usr/bin/bash

set -e

docker-compose run --rm build bash -e -c "
    cd /data/pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v france-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v andorra-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v guernsey-jersey-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v luxembourg-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v belgium-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v spain-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v canary-islands-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v morocco-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v madagascar-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v quebec-latest.osm.pbf
"


rm -f pbf/saint_pierre_et_miquelon-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/north-america/saint_pierre_et_miquelon-latest.osm.pbf
rm -f pbf/martinique-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/central-america/martinique-latest.osm.pbf
rm -f pbf/guadeloupe-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/central-america/guadeloupe-latest.osm.pbf
rm -f pbf/guyane-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/south-america/guyane-latest.osm.pbf
rm -f pbf/reunion-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/africa/reunion-latest.osm.pbf
rm -f pbf/mayotte-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/africa/mayotte-latest.osm.pbf
rm -f pbf/polynesie-latest.osm.pbf
wget -P pbf http://download.openstreetmap.fr/extracts/oceania/polynesie-latest.osm.pbf


docker-compose run --rm build bash -e -c "
    cd /data/pbf
    osmium merge -v --progress \
        --overwrite -o merge-latest.osm.pbf \
        france-latest.osm.pbf \
        andorra-latest.osm.pbf \
        guernsey-jersey-latest.osm.pbf \
        luxembourg-latest.osm.pbf \
        belgium-latest.osm.pbf \
        spain-latest.osm.pbf \
        canary-islands-latest.osm.pbf \
        morocco-latest.osm.pbf \
"

docker-compose run --rm build bash -e -c "
    ./ontology-build.sh && \\
    ruby ontology2layer.rb tourism \\
        ontology-tourism.json \\
        openmaptiles/layers/poi_tourism/poi_tourism.yaml \\
        openmaptiles/layers/poi_tourism/mapping.yaml \\
        openmaptiles/layers/poi_tourism/class.sql \\
        planetiler-openmaptiles/src/main/java/org/openmaptiles/layers/PoiTourismClass.java && \\
    ruby ontology2layer.rb city \\
        ontology-city.json \\
        openmaptiles/layers/poi_city/poi_city.yaml \\
        openmaptiles/layers/poi_city/mapping.yaml \\
        openmaptiles/layers/poi_city/class.sql \\
        planetiler-openmaptiles/src/main/java/org/openmaptiles/layers/PoiCityClass.java \\
"

generate() {
    AREA=$1
    ZOOM_MIN=$2
    ZOOM_MAX=$3
    JAVA_TOOL_OPTIONS="-Xmx2g" java -jar target/*with-deps.jar \
        --force --download \
        --osm-path=../pbf/${AREA}-latest.osm.pbf \
        --polygon=../bbox/${AREA}.poly \
        --minzoom=${ZOOM_MIN} \
        --maxzoom=${ZOOM_MAX} \
        --mbtiles=../mbtiles/openmaptiles-v3-${AREA}-z${ZOOM_MIN}-z${ZOOM_MAX}.mbtiles
}


cd planetiler-openmaptiles && \
git checkout src/main/java/org/openmaptiles/generated/ && \
./scripts/regenerate-openmaptiles.sh openmaptiles file://`pwd`/../ && \
./mvnw clean package -Dmaven.test.skip --no-snapshot-updates && \
generate "saint_pierre_et_miquelon" 7 14 && \
generate "martinique" 7 14 && \
generate "guadeloupe" 7 14 && \
generate "mayotte" 7 14 && \
generate "reunion" 7 14 && \
generate "polynesie" 7 14 && \
generate "guyane" 7 14 && \
generate "madagascar" 7 14 && \
generate "quebec" 7 14 && \
generate "merge" 7 14 && \
cd ..


# 8m39,435s
docker-compose run --rm build bash -e -c "
    cd /data/mbtiles
    tile-join --no-tile-size-limit \
        --attribution '<a href=\"https://www.teritorio.fr/\" target=\"_blank\">&copy; Teritorio</a> <a href=\"https://www.openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles</a> <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors</a>' \
        --force -o teritorio-dev.mbtiles \
        openmaptiles-v3-z0-z6.mbtiles \
        openmaptiles-v3-merge-z7-z14.mbtiles \
        openmaptiles-v3-saint_pierre_et_miquelon-z7-z14.mbtiles \
        openmaptiles-v3-martinique-z7-z14.mbtiles \
        openmaptiles-v3-guadeloupe-z7-z14.mbtiles \
        openmaptiles-v3-mayotte-z7-z14.mbtiles \
        openmaptiles-v3-reunion-z7-z14.mbtiles \
        openmaptiles-v3-polynesie-z7-z14.mbtiles \
        openmaptiles-v3-guyane-z7-z14.mbtiles \
        openmaptiles-v3-madagascar-z7-z14.mbtiles
        openmaptiles-v3-quebec-z7-z14.mbtiles
"

cp ontology-tourism.json ./mbtiles/teritorio-tourism-ontology-dev.json
cp ontology-city.json ./mbtiles/teritorio-city-ontology-dev.json
