#!/usr/bin/bash

set -e

docker-compose run --rm build bash -e -c "
    cd /data/pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v france-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v andorra-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v guernsey-jersey-latest.osm.pbf
    /usr/lib/python3-pyosmium/pyosmium-up-to-date -v spain-latest.osm.pbf
"

docker-compose run --rm build bash -e -c "
    cd /data/pbf
    osmium merge -v --progress \
        --overwrite -o merge.osm.pbf \
        france-latest.osm.pbf \
        andorra-latest.osm.pbf \
        guernsey-jersey-latest.osm.pbf \
        spain-latest.osm.pbf \
"

mkdir -p openmaptiles/data/
mv -f pbf/merge.osm.pbf openmaptiles/data/

cd openmaptiles
docker-compose down -v && \
rm -fr build
cd -

docker-compose run --rm build bash -e -c "
    ./ontology-build.sh && \\
    ruby ontology2layer.rb tourism \\
        ontology-tourism.json \\
        openmaptiles/layers/poi_tourism/poi_tourism.yaml \\
        openmaptiles/layers/poi_tourism/mapping.yaml \\
        openmaptiles/layers/poi_tourism/class.sql && \\
    ruby ontology2layer.rb city \\
        ontology-city.json \\
        openmaptiles/layers/poi_city/poi_city.yaml \\
        openmaptiles/layers/poi_city/mapping.yaml \\
        openmaptiles/layers/poi_city/class.sql \\
"

cd openmaptiles && \
make && \
make start-db && \
make import-data && \
make import-osm area=merge && \
make import-sql && \
make import-wikidata && \
make analyze-db && \
cp ../france-z7-z9.bbox data/merge.bbox && \
sed -i 's/MIN_ZOOM.*/MIN_ZOOM=7/' .env && \
sed -i 's/MAX_ZOOM.*/MAX_ZOOM=9/' .env && \
make generate-tiles area=merge && \
mv data/tiles.mbtiles ../mbtiles/openmaptiles-v3-france-z7-z9.mbtiles && \
cp ../france-z10-z14.bbox data/merge.bbox && \
sed -i 's/MIN_ZOOM.*/MIN_ZOOM=10/' .env && \
sed -i 's/MAX_ZOOM.*/MAX_ZOOM=14/' .env && \
make generate-tiles area=merge
mv data/tiles.mbtiles ../mbtiles/openmaptiles-v3-france-z10-z14.mbtiles
cd ..


# 8m39,435s
docker-compose run --rm build bash -e -c "
    cd /data/mbtiles
    tile-join --no-tile-size-limit \
        --attribution '<a href=\"https://www.teritorio.fr/\" target=\"_blank\">&copy; Teritorio</a> <a href=\"https://www.openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles</a> <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors</a>' \
        --force -o teritorio-dev.mbtiles \
        openmaptiles-v3-z0-z6.mbtiles \
        openmaptiles-v3-france-z7-z9.mbtiles \
        openmaptiles-v3-france-z10-z14.mbtiles
"

cp ontology-tourism.json ./mbtiles/teritorio-tourism-ontology-dev.json
cp ontology-city.json ./mbtiles/teritorio-city-ontology-dev.json
